services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass_123
      POSTGRES_DB: app_db
    ports:
      - "55432:5432"

  mongodb:
    image: mongo:7
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: app_user
      MONGO_INITDB_ROOT_PASSWORD: app_pass_123
    ports:
      - "27018:27017"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: app_pass_123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass_123
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
